### ISSUE TITLE
Use of Geometry.from_xml

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/plotter#10]
Before we were using Geometry.from_xml to get a bunch of information on cells and materials. Now that everything goes through libopenmc, there's almost no need for it. If I'm not mistaken, the only place we're actually using information from the `Geometry` object is to get the bounding box. Perhaps we should make that information available from C++/libopenmc itself. Given that we've discussed other uses of bounding boxes in C++, seems like that would be a useful addition there anyway.

**Comment by pshriwise** [comment]
True. At some point I'd like to get all domain information from C++. Some cell/material information is still scraped from the respective .xml files. This is a stopping point for viewing DAGMC models that I'd like to remove eventually.

**Comment by paulromano** [comment]
This was completed with #26.
