### ISSUE TITLE
Trouble running openmc-plotter for the first time

### ISSUE THREAD

**Issue by cdunn314** [openmc-dev/plotter#104]
Hi, I just installed the plotter using the following command in my openmc-env conda environment:
`$ pip install openmc-plotter`
I did not encounter any errors with the installation; however, when I tried to open the plotter with the following command:
`$ openmc-plotter`
I received the following error:
```
Traceback (most recent call last):
  File "/home/cdunn314/anaconda3/envs/openmc-env/bin/openmc-plotter", line 5, in <module>
    from openmc_plotter.__main__ import main
  File "/home/cdunn314/anaconda3/envs/openmc-env/lib/python3.10/site-packages/openmc_plotter/__main__.py", line 8, in <module>
    from PySide2 import QtCore, QtGui
ImportError: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: undefined symbol: krb5_ser_context_init, version krb5_3_MIT
```

I reinstalled PySide2, but I still encountered the same error when trying to run openmc-plotter. Does anyone know how to resolve this error?

**Comment by pshriwise** [comment]
Hi @cdunn314. Sorry to hear about the trouble! Hopefully we can get you up and running soon cause this tool is quite useful.

This appears to be related to the PyQt5 package, which PySide2 relies on. Ususally these symbol errors mean that some libraries/packages were installed using different package managers and the versions don't match up correctly. Could you indicate how these different components were installed (i.e. using `conda`, `pip`, or `apt-get`)?

  - python (it looks like this is part of the Conda environment, but I wanted to double-check)
  - openmc
  - pyside2 (if installed separately from the `openmc-plotter` package)
  - openmc-plotter

**Comment by billingsley-john** [comment]
Hi, I have also encountered the same issue. My installations may differ from @cdunn314's installation but these are how I installed each component:

- python (conda)
- openmc (conda)
- pyside2 (pip)
- openmc-plotter (pip)

I am running on WSL.

Thank you!

**Comment by paulromano** [comment]
@billingsley-john I believe the solution in your case is to make sure that pyside2 is installed from conda rather than pip.

**Comment by cdunn314** [comment]
After uninstalling Pyside2 using
`pip uninstall pyside2`
and reinstalling it with conda using
`conda install pyside2`,
I was able to open the plotter successfully. Thanks for your help!
