### ISSUE TITLE
Tally dock frozen

### ISSUE THREAD

**Issue by SteSeg** [openmc-dev/plotter#128]
Hi! I am having an issue with the tally dock WSL2. I inadvertently dragged it away from its position and now it is not possible to use it nor to drag it back in its default position. I have tried to uninstall and reinstall it in a conda environment via pip. I also tried installing it directly from source via `git clone` but it keeps opening with the tally dock in the wrong position.

**Comment by paulromano** [comment]
Have you tried deleting the `plot_settings.pkl` file in the directory containing the model you are plotting?

**Comment by SteSeg** [comment]
yes, I have. it does that for all the models I have, actually.

**Comment by SteSeg** [comment]
Found the solution. It is a general WSL issue that arises with several visualization tools (I just had the same problem with cubit). WSL saves the layout preferences of these tools in `~/.config/`, or in similar hidden folder in the home directory, and they stay there even if the program is uninstalled and reinstalled from scratch. In the case of this plotter the path is something like `~/.config/OpenMC`. It is sufficient to find that `OpenMC` folder in the hidden directory  and convert it to `.bak ` e.g.
```cmd
mv ~/.config/OpenMC ~/.config/OpenMC.bak
```

Even though this issue is not caused by the plotter this info might be useful for future users.

**Comment by pshriwise** [comment]
Thanks @SteSeg! Definitely helpful to know this for other users. I'm going to close this for now as it doesn't turn out to require any action in this repo, but I'm definitely going to make a mental note of this for others.
