### ISSUE TITLE
Matplotlib figure canvas on high DPI monitor

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/plotter#18]
One thing I've noticed is that the axis labels on the embedded matplotlib figure appear pretty small on my high DPI monitor (2560x1440 on a 14" screen). One way to fix the axis labels is:

```Python
from PySide2.QtCore import QCoreApplication, Qt
QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
```

but this ends up screwing up the rest of the GUI (as well as the splash screen).

**Comment by pshriwise** [comment]
I've noticed that too. I think have a way to handle it in the `FigureCanvas`. I'll add that in with some OSX fixes coming soon. Trying to handle some graphics tearing issues when scrolling on a Mac.
