### ISSUE TITLE
Double click not working?

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/plotter#27]
I just noticed that double-clicking doesn't seem to change the origin anymore. The updated coordinates show up in the text boxes for a moment while it is "Generating plot..." but the position never changes and then the coordinates displayed in the text boxes just get reset to what they were before.

**Comment by pshriwise** [comment]
I'm not having this same problem. Weird. I tried going back to a previous working version to see if an older `plot_settings.pkl` would cause that problem but it didn't seem to change for me - double-clicking still worked. :thinking:

**Comment by paulromano** [comment]
Hmm, weird. I'll try a few playing around with it more to see if I can narrow down the issue.

**Comment by paulromano** [comment]
Welp, now I can't reproduce this. Guess it was just some weird anomaly on my system :man_shrugging:
