### ISSUE TITLE
Ability to reset to default view without resetting colors / other preferences

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/plotter#28]
Sometimes I'm working with a model and I want to change the colors of certain materials / cells and move around in the model. Often, I just want to "zoom out" all the way back to the default view (ctrl+r), but when I do this, any color settings I've changed also get reset. It would be nice if there were an in-between option, or if resetting the view and resetting the color/other settings were two separate things.

**Comment by pshriwise** [comment]
Agreed! No reason that resetting the view should wipe out that other state. I'll make the (ctrl+r) shortcut a view reset only and add a button to the color dialog for resetting to the original color scheme. Sound good?

**Comment by paulromano** [comment]
Sounds great!

**Comment by pshriwise** [comment]
Addressed in #30
