### ISSUE TITLE
Add OpenMC version check

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/plotter#55]
The tool should require a minimum version of OpenMC and report a version in compatibility before loading the application. As of now, the only indication is some error in the terminal output -- usually buried by a Qt traceback. 

https://openmc.discourse.group/t/question-about-openmc-plotter/1050

**Comment by Shimwell** [comment]
Perhaps something like this will do the trick

if openmc.__version__ < 0.12.0:
    raise ImportError('openmc version of 0.12.0 or newer is required')

**Comment by pshriwise** [comment]
This has been addressed in #42 and updated in #59.
