### ISSUE TITLE
Image is generated twice when loading

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/plotter#67]
When the application is first opened, the functions for the id/material mapping are called twice.

**Comment by kkiesling** [comment]
I am not quite sure I can reproduce this. When you open the application, do you see `Reading materials XML file...` appear twice in the terminal? This is my terminal output when I load the test geometry in this repo. I don't see indication of double loading here.
![Screen Shot 2022-04-18 at 11 08 35 AM](https://user-images.githubusercontent.com/4060017/163837290-28b8e901-a034-4e3d-904f-bae8461ac7aa.png)

**Comment by pshriwise** [comment]
OpenMC isn't initialized twice, but a redundant call to `openmc.lib.id_map` and/or `openmc.lib.propety_map` occurs.

**Comment by kkiesling** [comment]
I think I figured out how it is getting called twice (or even more). Bare with me, this is a bit long, but I will link to as much source as possible.

So first, we know that [`makePlot()`](https://github.com/openmc-dev/plotter/blob/develop/openmc_plotter/plotmodel.py#L190) is being called 2x upon loading, when it should only be called once. Through backtrace, this is getting called through both [`loadGui()`](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L47) and [`applyChanges()`](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L584) (both call `generatePixMap()` --> `generatePlot()` --> `makePlot()`). Presumably, upon start up this should only be called with `loadGui` as there should be no "changes" to apply.

However, `applyChanges()` can also be called through updating menu options. In this case it is also being called on startup by various toggled options through the edit menu. The edit menu is updated [here](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L92) (in `loadGui` at startup) by calling [`updateEditMenu()`](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L405). [These three](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L409) edit options are what is ultimately calling `applyChanges()` [here](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L734), [here](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L740), and [here](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L807).

Now here is the complicated thing, those three options (masking, highlight, outline) have their state saved from the previous loading of the GUI. They are present in the `Edit` menu ("Enable ...") - shown in pic A.

Pic A:
![Screen Shot 2022-04-18 at 1 03 35 PM](https://user-images.githubusercontent.com/4060017/163855171-3764baf4-1014-423e-a3bf-5c485b2a9d41.png)

If any of those three options are checked (but _not_ the "Enable Overlap Coloring" option, not sure why that one is excluded), the check is saved for the next load. Pic B shows menu with all options checked before exiting. Pic C shows which options were checked after reloading, which means `applyChanges()` is called up to 3 times (once per option checked). If any of the 3 options in question are left unchecked, then they remain unchecked and `applyChanges()` is skipped.

Pic B:
![Screen Shot 2022-04-18 at 1 05 20 PM](https://user-images.githubusercontent.com/4060017/163855519-2070e16f-e5c1-4966-8c75-dbe340b9708c.png)]

Pic C:
![Screen Shot 2022-04-18 at 1 05 50 PM](https://user-images.githubusercontent.com/4060017/163855547-ea5b4576-a7c4-4b77-9058-59bb7f90dd70.png)

------ 

**So the TL;DR is that the state of the edit menu is saved for those three edit menu options and if they are checked, the call to `makePlot()` is essentially called for each checked item (so these methods in question can be called up to 3 extra times upon start up right now).**

**Comment by kkiesling** [comment]
You can reproduce the behavior by playing around with toggling those options before quitting the gui. If you uncheck all of them, you should have no additional `makePlot` calls than just the single one for loading the GUI.

**Comment by pshriwise** [comment]
Thanks for digging into that @kkiesling!

Tangentially, I didn't know the menu items would show up so nicely on OSX. That's cool to see 😁

**Comment by kkiesling** [comment]
So I guess the question on moving forward is, do you want the behavior of the GUI to be such that the state of the edit menu is saved? Because if not, I think it is just a simple removal of [these 3 lines](https://github.com/openmc-dev/plotter/blob/01663735afc91d77a7054484f47953448d21d74d/openmc_plotter/main_window.py#L409) to stop the additional loading at start up. But if you want the state to be saved, then I think there's not a way around the additional loading.

**Comment by pshriwise** [comment]
I do think it would be good for those settings to persist. When users are post-processing data it's inconvenient to have to re-select settings each time they open the plotter. Ideally, we can postpone the connections for state changes of these options to the data model until after the information from the `plot_settings.pkl` file has been applied.

**Comment by pshriwise** [comment]
I haven't looked into how much restructuring that would require, but I'm guessing it may require that we have separate methods to connect the different GUI objects to their respective methods. We can call those after the state of the objects has been set. IIRC those connections are made in the constructors right now.

**Comment by kkiesling** [comment]
I am definitely a novice with QT and GUI based things.. BUT it seems like it is not actually possible to prevent reloading if you want those checks to stay on in the edit menu. After the first (and desired) call to `makePlot()` all other calls are executed during app execution at [this line](https://github.com/openmc-dev/plotter/blob/develop/openmc_plotter/__main__.py#L77). And each time those options are toggled either on or off (from the gui while being used), `makePlot()` is triggered. So I think any place you want to set the state of those toggles, even through the loading of the `plot_settings.pkl` file, it will trigger the loading during execution anyway.

**Comment by pshriwise** [comment]
I'm fairly certain that a lot of the calls to `openmc.lib.id_map` are occurring in the call to `main.loadGui` beforehand. This is where the model state is read in from the `plot_settings.pkl` file. If you place print statements in `PlotImage.generatePixmap` and right above the line you indicated you'll see that several calls to `PlotImage.generatePixmap` (and in turn to `openmc.lib.id_map`) occur before we get to the `sys.exit(app.exec())` call. These are triggered by callbacks set on the menu items to update the image data when changed in `main.loadGui` 

We need a way to disable calls to `openmc.lib.id_map` until we're done loading model information and setting its state. I think some kind of attribute on the `PlotImage` object like "frozen" or something that's set to `True` during `loadGui` and `False` at the end would do the trick.

**Comment by pshriwise** [comment]
As an aside, I think [this line](https://github.com/openmc-dev/plotter/blob/cfc56d6ab57c81d591459a186c4fb5157ea75190/openmc_plotter/main_window.py#L114) should be removed. It allows the GUI to start loading before the image is ready to let users know that something is on the way, but it ends up resulting in a black box inside the window until a plot is available, so let's just go ahead and remove it.

**Comment by pshriwise** [comment]
Since I had it all in my head, I went ahead and took a crack at it in [this branch](https://github.com/pshriwise/plotter/tree/no_img_on_load). What do you think?

**Comment by kkiesling** [comment]
That's definitely an easier solution than I anticipated it being. It does the trick for me when I just tried it.

This does remind me of another question- do you want the "Enable Overlap Coloring" setting to be saved like the other three options? Right now it is not setup to be saved.

**Comment by pshriwise** [comment]
Awesome! I'll go ahead and submit a PR since I have it coded up already. 

Yeah, ideally that setting would persist too. Want to tackle that one?

**Comment by kkiesling** [comment]
Yep, can do

**Comment by paulromano** [comment]
Closed with the merging of #90
